services:
  academico-notificaciones:
    image: ${ACADEMICO_NOTIFICACIONES_IMAGE}
    container_name: academico-notificaciones
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production        
    networks:
      - academico-backend
    
networks:
  academico-backend:
    external: true
